import { Controller, Get, Header, Param, Res } from '@nestjs/common';
import {
  ApiOkResponse,
  ApiOperation,
  ApiParam,
  ApiTags,
} from '@nestjs/swagger';
import type { Response } from 'express';
import { basename } from 'node:path';
import { StorageService } from './storage.service';

@ApiTags('Storage')
@Controller('storage')
export class StorageController {
  constructor(private readonly storageService: StorageService) {}

  @Get('blobs/:token/:filename')
  @Header('Cross-Origin-Resource-Policy', 'cross-origin')
  @Header('X-Content-Type-Options', 'nosniff')
  @ApiParam({
    description: 'Signed storage token generated by the backend.',
    name: 'token',
  })
  @ApiParam({
    description: 'Download/display filename from the signed URL.',
    name: 'filename',
  })
  @ApiOperation({
    description:
      'Streams a signed blob URL for uploaded documents, previews, attachments, logos, and generated PDFs.',
    summary: 'Stream signed storage blob',
  })
  @ApiOkResponse({
    description:
      'Binary response with Content-Type and inline Content-Disposition from the stored blob.',
  })
  async proxyBlob(
    @Param('token') token: string,
    @Res() response: Response,
  ): Promise<void> {
    const blob = await this.storageService.getBlobForSignedToken(token);
    const stream = await this.storageService.readBlobStream(blob);
    const filename = basename(this.storageService.getSafeDownloadName(blob));

    response.type(blob.contentType ?? 'application/octet-stream');
    response.setHeader('Cache-Control', 'public, max-age=300');
    response.setHeader('Content-Length', blob.byteSize);
    response.setHeader(
      'Content-Disposition',
      `inline; filename="${filename.replaceAll('"', '\\"')}"`,
    );
    stream.on('error', () => {
      if (response.headersSent) {
        response.destroy();
        return;
      }

      response.status(500).end();
    });
    stream.pipe(response);
  }
}
