import { UnprocessableEntityException } from '@nestjs/common';
import forge from 'node-forge';
import type * as Forge from 'node-forge';

export const signaDefaultCertificateName = 'Signa Self-Host Autogenerated';
export const signingCertificatePrefix = 'signing_certificate:';
export const defaultSigningCertificateKey = 'default_signing_certificate';
export const timestampServerUrlKey = 'timestamp_server_url';

export type StoredSigningCertificate = {
  content_type?: string | null;
  data: string;
  filename?: string;
  internal_revocation?: StoredSigningCertificateRevocation | null;
  issuer?: string | null;
  password?: string;
  serial_number?: string | null;
  subject?: string | null;
  valid_from?: string | null;
  valid_to?: string | null;
};

export type StoredSigningCertificateRevocation = {
  crl_issuer_private_key_pem: string;
};

export type SigningCertificateInspection = {
  issuer: string | null;
  serial_number: string | null;
  subject: string | null;
  valid_from: string | null;
  valid_to: string | null;
};

export function buildStoredSigningCertificate(input: {
  buffer: Buffer;
  contentType?: string | null;
  filename?: string;
  password?: string;
}): StoredSigningCertificate {
  const inspection = inspectP12Certificate(input.buffer, input.password ?? '');

  return {
    content_type: input.contentType ?? 'application/x-pkcs12',
    data: input.buffer.toString('base64'),
    filename: input.filename,
    password: input.password ?? '',
    ...inspection,
  };
}

export function generateSignaDefaultCertificate(): StoredSigningCertificate {
  const rootKeys = forge.pki.rsa.generateKeyPair(2048);
  const rootCert = createCertificate({
    commonName: 'Signa Root CA',
    isCa: true,
    issuerCert: null,
    issuerKey: rootKeys.privateKey,
    keys: rootKeys,
    organization: 'Signa',
    validityYears: 100,
  });
  const intermediateKeys = forge.pki.rsa.generateKeyPair(2048);
  const intermediateCert = createCertificate({
    commonName: 'Signa Sub-CA',
    isCa: true,
    issuerCert: rootCert,
    issuerKey: rootKeys.privateKey,
    keys: intermediateKeys,
    organization: 'Signa',
    validityYears: 100,
  });
  const signerKeys = forge.pki.rsa.generateKeyPair(2048);
  const signerCert = createCertificate({
    commonName: 'Signa',
    isCa: false,
    issuerCert: intermediateCert,
    issuerKey: intermediateKeys.privateKey,
    keys: signerKeys,
    organization: 'Signa',
    validityYears: 100,
  });
  const asn1 = forge.pkcs12.toPkcs12Asn1(
    signerKeys.privateKey,
    [signerCert, intermediateCert, rootCert],
    '',
    { algorithm: '3des' },
  );
  const der = forge.asn1.toDer(asn1).getBytes();
  const buffer = Buffer.from(der, 'binary');

  return {
    data: buffer.toString('base64'),
    filename: 'signa-self-host-autogenerated.p12',
    internal_revocation: {
      crl_issuer_private_key_pem: forge.pki.privateKeyToPem(
        intermediateKeys.privateKey,
      ),
    },
    password: '',
    ...certificateInspection(signerCert),
  };
}

export function inspectP12Certificate(
  buffer: Buffer,
  password: string,
): SigningCertificateInspection {
  try {
    const p12 = parseP12(buffer, password);
    const certBag = p12.getBags({
      bagType: forge.pki.oids.certBag,
    })[forge.pki.oids.certBag]?.[0];
    const cert = certBag?.cert;

    if (!cert) {
      throw new Error('PKCS#12 certificate was not found');
    }

    return certificateInspection(cert);
  } catch (error) {
    throw new UnprocessableEntityException({
      error:
        error instanceof Error
          ? `Invalid signing certificate: ${error.message}`
          : 'Invalid signing certificate',
    });
  }
}

export function p12BufferFromStoredCertificate(
  certificate: StoredSigningCertificate,
): Buffer {
  return Buffer.from(certificate.data, 'base64');
}

export function parseStoredSigningCertificate(
  value: string,
): StoredSigningCertificate | null {
  try {
    const parsed = JSON.parse(value) as unknown;

    if (!isRecord(parsed) || typeof parsed.data !== 'string') {
      return null;
    }

    return {
      content_type:
        typeof parsed.content_type === 'string' ? parsed.content_type : null,
      data: parsed.data,
      filename: typeof parsed.filename === 'string' ? parsed.filename : '',
      internal_revocation: parseInternalRevocation(parsed.internal_revocation),
      issuer: typeof parsed.issuer === 'string' ? parsed.issuer : null,
      password: typeof parsed.password === 'string' ? parsed.password : '',
      serial_number:
        typeof parsed.serial_number === 'string' ? parsed.serial_number : null,
      subject: typeof parsed.subject === 'string' ? parsed.subject : null,
      valid_from:
        typeof parsed.valid_from === 'string' ? parsed.valid_from : null,
      valid_to: typeof parsed.valid_to === 'string' ? parsed.valid_to : null,
    };
  } catch {
    return null;
  }
}

export function hasInternalRevocation(
  certificate: StoredSigningCertificate,
): boolean {
  return Boolean(
    certificate.internal_revocation?.crl_issuer_private_key_pem?.trim(),
  );
}

function parseInternalRevocation(
  value: unknown,
): StoredSigningCertificateRevocation | null {
  if (
    !isRecord(value) ||
    typeof value.crl_issuer_private_key_pem !== 'string' ||
    !value.crl_issuer_private_key_pem.trim()
  ) {
    return null;
  }

  return {
    crl_issuer_private_key_pem: value.crl_issuer_private_key_pem,
  };
}

function parseP12(buffer: Buffer, password: string): Forge.pkcs12.Pkcs12Pfx {
  const der = forge.util.createBuffer(buffer.toString('binary'));
  const asn1 = forge.asn1.fromDer(der);

  return forge.pkcs12.pkcs12FromAsn1(asn1, false, password);
}

function createCertificate(input: {
  commonName: string;
  isCa: boolean;
  issuerCert: Forge.pki.Certificate | null;
  issuerKey: Forge.pki.rsa.PrivateKey;
  keys: Forge.pki.rsa.KeyPair;
  organization: string;
  validityYears: number;
}): Forge.pki.Certificate {
  const cert = forge.pki.createCertificate();
  const now = new Date();

  cert.publicKey = input.keys.publicKey;
  cert.serialNumber = forge.util.bytesToHex(forge.random.getBytesSync(20));
  cert.validity.notBefore = now;
  cert.validity.notAfter = new Date(now);
  cert.validity.notAfter.setFullYear(now.getFullYear() + input.validityYears);

  const attrs = [
    { name: 'countryName', value: 'US' },
    { name: 'organizationName', value: input.organization },
    { name: 'commonName', value: input.commonName },
  ];

  cert.setSubject(attrs);
  cert.setIssuer(
    input.issuerCert ? input.issuerCert.subject.attributes : attrs,
  );
  cert.setExtensions([
    {
      cA: input.isCa,
      critical: true,
      name: 'basicConstraints',
    },
    {
      critical: true,
      digitalSignature: !input.isCa,
      keyCertSign: input.isCa,
      name: 'keyUsage',
    },
    {
      name: 'subjectKeyIdentifier',
    },
  ]);
  cert.sign(input.issuerKey, forge.md.sha256.create());

  return cert;
}

function certificateInspection(
  cert: Forge.pki.Certificate,
): SigningCertificateInspection {
  return {
    issuer: formatName(cert.issuer.attributes),
    serial_number: cert.serialNumber,
    subject: formatName(cert.subject.attributes),
    valid_from: cert.validity.notBefore.toISOString(),
    valid_to: cert.validity.notAfter.toISOString(),
  };
}

function formatName(attributes: Forge.pki.CertificateField[]): string {
  return attributes
    .map(
      (attribute) =>
        `${attribute.shortName ?? attribute.name}=${formatAttributeValue(attribute.value)}`,
    )
    .join(', ');
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return Boolean(value && typeof value === 'object' && !Array.isArray(value));
}

function formatAttributeValue(value: unknown): string {
  if (
    typeof value === 'string' ||
    typeof value === 'number' ||
    typeof value === 'boolean' ||
    typeof value === 'bigint'
  ) {
    return String(value);
  }

  return '';
}
